# docker-compose.yml

version: '3'
services:
  fastapi-celery:
    build: .
    ports:
      - "8000:8000"
    environment:
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis
  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
